# Site settings
title: angular-jekyll-editor test site
keywords: angular, jekyll, editor
baseurl: "" # the subpath of your site, e.g. /blog/
gems:
    - jekyll-sitemap

# Build settings
sass:
    sass_dir: assets/_sass
    style: :compressed

# see. best practices DOs and DONTs for details about following section
# http://www.elegantthemes.com/blog/tips-tricks/best-practices-for-using-categories-and-tags-in-wordpress
avail_tags: rada, zastupitelstvo, územníplán, kultura, sport
avail_cats: AKCE, JEDNÁNÍ, PLÁNY, ÚŘEDNÍ_DESKA
avail_filecats: SMLOUVY, ZÁPISY, VÝKRESY, GRAFIKA, UZÁVĚRKY
