# Site settings
title: angular-jekyll-editor test site
keywords: angular, jekyll, editor
baseurl: "" # the subpath of your site, e.g. /blog/
gems:
    - jekyll-sitemap

# Build settings
sass:
    sass_dir: assets/_sass
    style: :compressed
